name: use Reuse workflows
on:
  workflow_dispatch:

jobs:
  calling-a-reusable-wf-same-repo:
    uses: ./.github/workflows/reusable.yaml
  using-reusable-wf-outputs:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-same-repo
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf-same-repo.outputs.date }}
